In [16]:
import pandas as pd
import re
url = "/content/sample_data/train.csv"
laasya = pd.read_csv(url)
laasya['Mileage'] = data['Mileage'].apply(lambda x: re.sub(r'[^\d.]', '', str(x)))
laasya['Engine'] = data['Engine'].apply(lambda x: re.sub(r'[^\d.]', '', str(x)))
laasya['Power'] = data['Power'].apply(lambda x: re.sub(r'[^\d.]', '', str(x)))
laasya['New_Price'] = data['New_Price'].apply(lambda x: re.sub(r'[^\d.]', '', str(x)))
laasya.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,NaN,NaN,NaN,5.0,NaN,12.50
1,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,13,1199,88.7,5.0,8.61,4.50
2,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,NaN,NaN,NaN,7.0,NaN,6.00
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,NaN,NaN,NaN,5.0,NaN,17.74
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,First,NaN,NaN,NaN,5.0,NaN,3.50